export const FETCH_TEST_DATA = "FETCH_TEST_DATA";
export const FETCH_TRAINING_DATA = "FETCH_TRAINING_DATA";
export const FETCH_FULL_TRAINING_DATA = "FETCH_FULL_TRAINING_DATA";

export const TEST_DATA_LOADED = "TEST_DATA_LOADED";
export const TRAINING_DATA_LOADED = "TRAINING_DATA_LOADED";
export const FULL_TRAINING_DATA_LOADED = "FULL_TRAINING_DATA_LOADED";

export const ERROR_FETCH_TEST_DATA = "ERROR_FETCH_TEST_DATA";